"""官方已发布种子词表。"""

SEED_POINTS = [
    {"kind": "poem", "level": "L1", "prompt": "默写李白《静夜思》", "answer": "床前明月光，疑是地上霜。举头望明月，低头思故乡。", "tags": "古诗;李白;课内必背", "source": "部编小学"},
    {"kind": "poem", "level": "L1", "prompt": "默写孟浩然《春晓》", "answer": "春眠不觉晓，处处闻啼鸟。夜来风雨声，花落知多少。", "tags": "古诗;孟浩然;课内必背", "source": "部编小学"},
    {"kind": "poem", "level": "L1", "prompt": "默写王之涣《登鹳雀楼》", "answer": "白日依山尽，黄河入海流。欲穷千里目，更上一层楼。", "tags": "古诗;王之涣;课内必背", "source": "部编小学"},
    {"kind": "poem", "level": "L1", "prompt": "默写骆宾王《咏鹅》", "answer": "鹅，鹅，鹅，曲项向天歌。白毛浮绿水，红掌拨清波。", "tags": "古诗;骆宾王;课内必背", "source": "部编小学"},
    {"kind": "poem", "level": "L1", "prompt": "默写李绅《悯农》", "answer": "锄禾日当午，汗滴禾下土。谁知盘中餐，粒粒皆辛苦。", "tags": "古诗;李绅;课内必背", "source": "部编小学"},
    {"kind": "poem", "level": "L2", "prompt": "默写李白《望庐山瀑布》", "answer": "日照香炉生紫烟，遥看瀑布挂前川。飞流直下三千尺，疑是银河落九天。", "tags": "古诗;李白;课内拓展", "source": "部编小学"},
    {"kind": "poem", "level": "L3", "prompt": "默写苏轼《题西林壁》", "answer": "横看成岭侧成峰，远近高低各不同。不识庐山真面目，只缘身在此山中。", "tags": "古诗;苏轼;小升初高频", "source": "部编小学"},
    {"kind": "poem", "level": "L2", "prompt": "默写柳宗元《江雪》", "answer": "千山鸟飞绝，万径人踪灭。孤舟蓑笠翁，独钓寒江雪。", "tags": "古诗;柳宗元", "source": "部编小学"},
    {"kind": "poem", "level": "L2", "prompt": "默写孟郊《游子吟》", "answer": "慈母手中线，游子身上衣。临行密密缝，意恐迟迟归。谁言寸草心，报得三春晖。", "tags": "古诗;孟郊", "source": "部编小学"},
    {"kind": "poem", "level": "L3", "prompt": "默写白居易《赋得古原草送别》前四句", "answer": "离离原上草，一岁一枯荣。野火烧不尽，春风吹又生。", "tags": "古诗;白居易;小升初高频", "source": "部编小学"},
    {"kind": "poem", "level": "L3", "prompt": "默写王昌龄《出塞》", "answer": "秦时明月汉时关，万里长征人未还。但使龙城飞将在，不教胡马度阴山。", "tags": "古诗;王昌龄;小升初高频", "source": "部编小学"},
    {"kind": "poem", "level": "L1", "prompt": "欲穷千里目，______。", "answer": "更上一层楼", "tags": "名句填空;王之涣", "source": "真题高频"},
    {"kind": "idiom", "level": "L1", "prompt": "比喻死守狭隘经验、不知变通（四字）", "answer": "守株待兔", "tags": "成语", "source": "课内必背"},
    {"kind": "idiom", "level": "L1", "prompt": "出了问题及时补救，还不算晚（四字）", "answer": "亡羊补牢", "tags": "成语", "source": "课内必背"},
    {"kind": "idiom", "level": "L1", "prompt": "做了多余的事，反而把事情弄坏（四字）", "answer": "画蛇添足", "tags": "成语", "source": "课内必背"},
    {"kind": "idiom", "level": "L2", "prompt": "自己骗自己，明明掩盖不了的事实（四字）", "answer": "掩耳盗铃", "tags": "成语", "source": "课内拓展"},
    {"kind": "idiom", "level": "L2", "prompt": "办事刻板，不知随着情况变化（四字）", "answer": "刻舟求剑", "tags": "成语", "source": "课内拓展"},
    {"kind": "idiom", "level": "L2", "prompt": "见识狭窄，看不到更大的世界（四字）", "answer": "井底之蛙", "tags": "成语", "source": "课内拓展"},
    {"kind": "idiom", "level": "L2", "prompt": "对不懂的人讲道理，白费口舌（四字）", "answer": "对牛弹琴", "tags": "成语", "source": "课内拓展"},
    {"kind": "idiom", "level": "L2", "prompt": "倚仗别人的权势欺压人（四字）", "answer": "狐假虎威", "tags": "成语", "source": "课内拓展"},
    {"kind": "idiom", "level": "L3", "prompt": "没有真才实学，混在行家里面充数（四字）", "answer": "滥竽充数", "tags": "成语;小升初高频", "source": "真题高频"},
    {"kind": "idiom", "level": "L1", "prompt": "复习旧知识，能有新体会（四字）", "answer": "温故知新", "tags": "成语", "source": "课内必背"},
    {"kind": "zi", "level": "L1", "prompt": "看拼音写字：jǐ（自己）", "answer": "己", "tags": "易错字;己已巳", "source": "课内必背"},
    {"kind": "zi", "level": "L1", "prompt": "看拼音写字：yǐ（已经）", "answer": "已", "tags": "易错字;己已巳", "source": "课内必背"},
    {"kind": "zi", "level": "L1", "prompt": "看拼音写字：wèi（未来）", "answer": "未", "tags": "易错字;未末", "source": "课内必背"},
    {"kind": "zi", "level": "L1", "prompt": "看拼音写字：mò（期末）", "answer": "末", "tags": "易错字;未末", "source": "课内必背"},
    {"kind": "zi", "level": "L1", "prompt": "看拼音写字：chuān（穿衣服）", "answer": "穿", "tags": "易错字", "source": "课内必背"},
    {"kind": "zi", "level": "L2", "prompt": "看拼音写字：dài（爱戴）", "answer": "戴", "tags": "易错字;戴带", "source": "课内拓展"},
    {"kind": "zi", "level": "L2", "prompt": "看拼音写字：biàn（辩论）", "answer": "辩", "tags": "易错字;辩辨辫", "source": "课内拓展"},
    {"kind": "zi", "level": "L2", "prompt": "看拼音写字：hòu（时候）", "answer": "候", "tags": "易错字;侯候", "source": "课内拓展"},
    {"kind": "zi", "level": "L3", "prompt": "看拼音写字：liáng（高粱）", "answer": "粱", "tags": "易错字;梁粱;小升初高频", "source": "真题高频"},
    {"kind": "zi", "level": "L3", "prompt": "看拼音写字：jí（即使）", "answer": "即", "tags": "易错字;即既", "source": "真题高频"},
]
